<?php

/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace MoufTest\Model\Dao;

use MoufTest\Model\Dao\Generated\BrandBaseDao;

/**
 * The BrandDao class will maintain the persistence of BrandBean class into the brands table.
 */
class BrandDao extends BrandBaseDao
{

}
