<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace MoufTest\Model\Bean;

use MoufTest\Model\Bean\Generated\BrandBaseBean;

/**
 * The BrandBean class maps the 'brands' table in database.
 */
class BrandBean extends BrandBaseBean
{

}