<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

namespace MoufTest\Model\Bean;

use MoufTest\Model\Bean\Generated\CarBaseBean;

/**
 * The CarBean class maps the 'cars' table in database.
 */
class CarBean extends CarBaseBean
{
    
}